e_p_django/e_p_django/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# noinspection PyUnresolvedReferences
from e_p_django.start_page.views import UserLoginView

urlpatterns = [
    path('schools/', include('e_p_django.start_page.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='registration/home.html'), name='home')
    path('', UserLoginView.as_view(), name='home'),
    path('select2/', include('django_select2.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

e_p_django/rooms/urls.py
from . import views
from django.urls import path
app_name = 'rooms'

urlpatterns = [
    path('<int:pk>/', views.RoomsView.as_view(), name='rooms'),
    path('create-room/<int:pk>/', views.RoomCreate.as_view(), name='room-create'),
    path('del-room/<int:pk>/', views.RoomDelete.as_view(), name='room-delete'),
    path('update-room/<int:pk>/', views.RoomUpdate.as_view(), name='room-update'),
]

e_p_django/schedules/urls.py
from django.urls import path

from . import views
app_name = 'schedules'

urlpatterns = [
    path('<int:pk>/', views.ScheduleView.as_view(), name='schedules'),
    path('create-schedule/<int:pk>/', views.ScheduleCreate.as_view(), name='schedule-create'),
    path('delete-schedule/<int:pk>/', views.ScheduleDelete.as_view(), name='schedule-delete'),
    path('update-schedule/<int:pk>/', views.ScheduleUpdate.as_view(), name='schedule-update'),
]

e_p_django/start_page/urls.py
from django.urls import path, include

from . import views
from e_p_django.schools.views import SchoolView


app_name = 'start_page'

urlpatterns = [
    path('register', views.UserRegisterView.as_view(), name='register'),
    path('login', views.UserLoginView.as_view(), name='login'),
    path('', SchoolView.as_view(), name='schools'),
    path('details/', include('e_p_django.schools.urls')),
    path('profile/', include('e_p_django.user_profile.urls'))
]

e_p_django/start_page/forms.py
from django.contrib.auth.models import User
from django import forms


class UserFormRegister(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label='Hasło')

    class Meta:
        labels = {'username': 'Login',
                  'email': 'Email'}
        error_messages = {
            'username': {
                'unique': 'Użytkownik z tym loginem już istnieje.'
            }
        }
        model = User
        fields = ['username', 'email', 'password']


class UserFormLogin(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

e_p_django/start_page/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user
from django.views import generic

from .forms import UserFormRegister, UserFormLogin
from e_p_django.schools import models


class UserLoginView(generic.View):
    """View for user login"""
    form_class = UserFormLogin
    template_name = 'registration/home.html'

    def get(self, request):
        form = self.form_class()
        user = get_user(request)
        if user.is_authenticated:
            return redirect('start_page:schools')
        else:
            return render(request, self.template_name, {'form': form})

    def post(self, request):
        if request.POST.get('submit', ) == 'sign-in':
            form = self.form_class()
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('start_page:schools')
            else:
                messages.error(request, "Błędny login bądź hasło")

            return render(request, self.template_name, {'form': form})
        elif request.POST.get('submit', ) == 'sign-up':
            return redirect('start_page:register')


class UserRegisterView(generic.View):
    """View for user registration"""
    form_class = UserFormRegister
    template_name = 'registration/register.html'

    # display blank form
    def get(self, request):
        form = self.form_class()

        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        email = request.POST['email']
        if models.User.objects.filter(email=email):
            messages.error(request, "Użytkownik z takim adresem email już istnieje.")
        elif form.is_valid():
            user = form.save(commit=False)
            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            # returns User object if credentials are correct
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('start_page:schools')

        return render(request, self.template_name, {'form': form})


# class ScheduleView(generic.ListView, )


# class ScheduleView(generic.ListView):
#     model = models.Schedule
#     template_name = 'start_page/schedules.html'
#     context_object_name = 'all_schedules'
#
#     def get_queryset(self):
#         user = self.request.user
#         return models.Schedule.objects.filter(school_id=user.id)

e_p_django/start_page/templates/start_page/index.html
{% extends 'start_page/base.html' %}
{% block schedules_active %}active{% endblock %}

{% block body %}
    <a role="button" href="{% url 'start_page:schedule-add' %}" class="btn btn-success btn-sm">Dodaj plan</a>
<div class="-container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
{#            <h3>{{ schedule.user }}'s Schedules</h3>#}
        </div>
        {% if all_schedules %}
            {% for schedule in all_schedules %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'start_page:detail' schedule.id %}"></a>
                        <div class="caption">
                            <h2>{{ schedule.name }}</h2>
                            <h4>{{ schedule.school_year }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'start_page:detail' schedule.id %}" class="btn btn-primary btn-sm" role="button">Pokaz szczegoly</a>

                            <!-- Delete Album -->
                            <form action="{% url 'start_page:schedule-delete' schedule.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="schedule_id" value="{{ schedule.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj plan
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are subjects -->
    {% if subjects %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Przedmioty</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nazwa przedmiotu</th>
                                    <th>Skrocona nazwa przedmiotu</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for sub in subjects %}
                                    <tr>
                                        <td>{{ sub.name }}</td>
                                        <td>{{ sub.album.short_name }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

e_p_django/start_page/templates/start_page/registration_form.html
{% extends 'start_page/base.html' %}
{% block title %} Rejestracja {% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Stwórz nowe konto</h3>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'start_page/form_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Zatwierdz</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}