e_p_django/e_p_django/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# noinspection PyUnresolvedReferences
from e_p_django.start_page.views import UserLoginView

urlpatterns = [
    path('schools/', include('e_p_django.start_page.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='registration/home.html'), name='home')
    path('', UserLoginView.as_view(), name='home'),
    path('select2/', include('django_select2.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

e_p_django/lessons_panel/urls.py
from django.urls import path

from . import views
app_name = 'lessons_panel'

urlpatterns = [
    path('<int:pk>/', views.LessonsPanelView.as_view(), name='lessons-panel'),
    path('ajax/load-schedules/', views.load_schedules, name='ajax_load_schedules'),
    path('ajax/load-schedule-panel/', views.load_schedule_panel, name='ajax_load_schedule_panel'),
    path('del-lesson/<int:pk>/', views.LessonDelete.as_view(), name='lesson_delete'),
    path('update-lesson/<int:pk>/', views.LessonUpdate.as_view(), name='lesson_update'),
    path('render/pdf/<int:pk>/', views.Pdf.as_view(), name='render_table')

    # path('selected-class/<int:pk>/', views.SelectClass.as_view(), name='selected-class')
]

e_p_django/rooms/urls.py
from . import views
from django.urls import path
app_name = 'rooms'

urlpatterns = [
    path('<int:pk>/', views.RoomsView.as_view(), name='rooms'),
    path('create-room/<int:pk>/', views.RoomCreate.as_view(), name='room-create'),
    path('del-room/<int:pk>/', views.RoomDelete.as_view(), name='room-delete'),
    path('update-room/<int:pk>/', views.RoomUpdate.as_view(), name='room-update'),
]

e_p_django/lessons_panel/models.py
from django.db import models
from django.urls import reverse

from e_p_django.classes_app.models import Class
from e_p_django.schedules.models import Schedule
from e_p_django.rooms.models import Room
from e_p_django.subjects.models import Subject
from e_p_django.teachers.models import Teacher


class Group(models.Model):

    class Meta:
        managed = True
        db_table = 'group'


class Lesson(models.Model):
    days_choices = (('1', 'Pon'), ('2', 'Wt'), ('3', 'Śr'), ('4', 'Czw'), ('5', 'Pt'), ('6', 'Sob'), ('7', 'Nie'))
    class_field = models.ForeignKey(Class, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, default=None, null=True, blank=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)  # Field name made lowercase.
    room = models.ForeignKey(Room, models.DO_NOTHING)  # Field name made lowercase.
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)  # Field name made lowercase.
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, default=None)
    lesson_number = models.IntegerField()
    day = models.CharField(default=None, max_length=20, choices=days_choices)

    def get_absolute_url(self):
        return reverse('start_page:schools:lessons_panel:lessons-panel', kwargs={'pk': self.schedule.school_id})

    class Meta:
        managed = True
        db_table = 'lesson'

e_p_django/lessons_panel/forms.py
from django import forms

from .models import Lesson
from schedules.models import Schedule
from schools.models import School
from subjects.models import Subject
from rooms.models import Room
from teachers.models import Teacher


class LessonForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        work_dict = kwargs.pop('work_dict', None)
        max_lessons = kwargs.pop('max_lessons', None)
        school_pk = kwargs.pop('school_pk', None)
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        if work_dict:
            work_dict = ((str(key), value) for key, value in work_dict.items())
            if work_dict:
                self.fields['day'] = forms.ChoiceField(required=True, choices=work_dict,
                                                       widget=forms.Select(), label="Dzień")
        if max_lessons:
            max_lessons = ((i, i) for i in range(1, max_lessons + 1))
            if max_lessons:
                self.fields['lesson_number'] = forms.ChoiceField(required=True, choices=max_lessons,
                                                                 widget=forms.Select(), label="Numer lekcji")
        if school_pk:
            self.fields['subject'].queryset = Subject.objects.filter(school_id=school_pk)
            self.fields['teacher'].queryset = Teacher.objects.filter(school_id=school_pk)
            self.fields['room'].queryset = Room.objects.filter(school_id=school_pk)

    class Meta:
        labels = {
            # 'group': 'Grupa',
            'subject': 'Przedmiot',
            'teacher': 'Prowadzący',
            'room': 'Pokój',
            'lesson_number': 'Numer lekcji',
            'day': 'Dzień'
        }
        model = Lesson
        fields = ['subject', 'teacher', 'room', 'lesson_number', 'day']


class ScheduleCombo(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        school_pk = kwargs.pop('school_pk', None)
        class_id = kwargs.pop('class_id', None)
        schedule_id = kwargs.pop('schedule_id', None)
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        if school_pk is not None:
            school = School.objects.get(id=school_pk)
            class_field = self.fields['class_field']
            class_field.queryset = school.class_set.all()
            if class_id:
                class_field.initial = class_id
            schedule_field = self.fields['schedule']
            if schedule_id and class_id:
                schedule_field.queryset = Schedule.objects.filter(class_field_id=int(class_id))
                schedule_field.initial = schedule_id
            else:
                schedule_field.queryset = school.schedule_set.none()

        if 'schedule' in self.data:
            try:
                class_id = int(self.data.get('class_field'))
                self.fields['schedule'].queryset = Schedule.objects.filter(class_field_id=class_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['schedule'].queryset = self.instance.class_field.schedule_set.order_by('name')

    class Meta:
        labels = {
            'class_field': 'Klasa',
            'schedule': 'Rok'
        }
        model = Lesson
        fields = ['class_field', 'schedule']

e_p_django/lessons_panel/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy, reverse
from django.contrib import messages

from .forms import LessonForm
from .forms import ScheduleCombo
from .models import Lesson
from schools.models import School
from schedules.models import Schedule
from .render import Render


def make_schedule_panel(pk):
    days_dict = {1: "Pon", 2: "Wt", 3: "Śr", 4: "Czw", 5: "Pt", 6: "Sob", 7: "Nie"}
    school_object = School.objects.get(id=pk)
    max_lessons = school_object.max_lessons
    work_dict = days_dict.copy()
    if school_object.weekend_days:
        for key, value in list(work_dict.items()):
            if str(key) in school_object.weekend_days or value in school_object.weekend_days:
                del work_dict[key]
    return max_lessons, school_object, work_dict


class LessonsPanelView(generic.TemplateView):
    template_name = 'lessons_panel/lesson_add.html'

    def get(self, request, pk, *args, **kwargs):
        class_id = kwargs.pop('class_value', None)
        if not class_id:
            class_id = request.COOKIES.get('class_value')
        schedule_id = kwargs.pop('schedule_value', None)
        if not schedule_id:
            schedule_id = request.COOKIES.get('schedule_value')
        schedules = ScheduleCombo(school_pk=pk, class_id=class_id, schedule_id=schedule_id)
        max_lessons, school_object, work_dict = make_schedule_panel(pk)
        lesson_form = LessonForm(work_dict=work_dict, max_lessons=max_lessons, school_pk=pk)

        context = self.get_context_data(
            lesson_form=lesson_form,
            schedule_object=schedules,
            school_object=school_object,
            max_lessons=range(1, max_lessons + 1),
            work_dict=work_dict
        )

        return self.render_to_response(context)

    def post(self, request, pk, *args, **kwargs):
        post_data = request.POST
        lesson_form = LessonForm(post_data)
        schedules = ScheduleCombo(post_data, school_pk=pk)

        if schedules.is_valid():
            class_id = post_data['class_field']
            schedule_id = post_data['schedule']

            if lesson_form.is_valid():
                lessons_list = Lesson.objects.filter(
                    schedule_id=schedule_id,
                    lesson_number=post_data['lesson_number'],
                    day=post_data['day'])
                if not lessons_list:
                    self.form_save(lesson_form, class_id, schedule_id)
                    messages.success(request, "Dodano lekcje")
                    response = self.get(request, pk, class_value=class_id, schedule_value=schedule_id)
                    response.set_cookie("class_value", class_id)
                    response.set_cookie("schedule_value", schedule_id)
                    return response
                else:
                    messages.warning(request, "Istnieje już lekcja na tej pozycji.")
                    response = self.get(request, pk, class_value=class_id, schedule_value=schedule_id)
                    response.set_cookie("class_value", class_id)
                    response.set_cookie("schedule_value", schedule_id)
                    return response
        return self.get(request, pk)

    def form_save(self, form, class_id, schedule_id):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        obj.class_field_id = class_id
        obj.schedule_id = schedule_id
        obj.save()
        return obj


def load_schedules(request):
    class_id = request.GET.get('class_field')
    schedules_year = Schedule.objects.filter(class_field_id=int(class_id))
    return render(request, 'lessons_panel/schedules_dropdown_list.html', {'schedules_year': schedules_year})


def load_schedule_panel(request):
    color_directory = {1: "lightblue", 2: "lightgreen", 3: "lightyellow", 4: "lightpink",
                       5: "tomato", 6: "lightseagreen", 7: "violet", 8: "LightGrey", 9: "aquamarine",
                       10: "lightcoral", 11: "burlywood", 12: "lightsteelblue", 13: "mediumpurple", 14: "white"}
    schedule_id = request.GET.get('schedule')
    schedule_object = Schedule.objects.get(id=schedule_id)
    school_id = schedule_object.school_id
    lessons_list = schedule_object.lesson_set.all()
    max_lessons, school_object, work_dict = make_schedule_panel(school_id)
    assoc_col_name = {}
    if lessons_list:
        for lesson in lessons_list:
            lesson.day = int(lesson.day)
        i = 1
        for lesson in lessons_list:
            assoc_size = len(assoc_col_name)
            if lesson.subject.short_name:
                if lesson.subject.short_name not in assoc_col_name.values():
                    assoc_col_name[i] = lesson.subject.short_name
            else:
                if lesson.subject.name not in assoc_col_name.values():
                    assoc_col_name[i] = lesson.subject.name
            if len(assoc_col_name) > assoc_size:
                i += 1
    table_string = "<style>table,td,th{ table-layout: fixed; width: 100%; border: 1px solid lightgrey;}</style>" \
                   "<tbody id='table_body'>"

    for key, value in work_dict.items():
        table_string += "<tr><td>" + value + "</td>"
        if lessons_list:
            for i in range(1, max_lessons + 1):
                if_inside = False
                for lesson in lessons_list:
                    if lesson.lesson_number == i and lesson.day == key and not if_inside:
                        delete_url = reverse('start_page:schools:lessons_panel:lesson_delete', args=[lesson.id])
                        update_url = reverse('start_page:schools:lessons_panel:lesson_update', args=[lesson.id])
                        if lesson.subject.short_name:
                            subject_name = lesson.subject.short_name
                        else:
                            subject_name = lesson.subject.name
                        number_color = 14
                        for number, name in assoc_col_name.items():
                            if name == subject_name:
                                number_color = number
                                break
                        color = color_directory[number_color]

                        table_string += "<td style='background-color:" + color + ";text-align: center;'><div>" \
                                        + lesson.subject.short_name + "<br>" + \
                                        lesson.room.room_number + \
                                        "<br>" + lesson.teacher.name + " " + lesson.teacher.surname + "<br>" + \
                                        "<a href=\"" + update_url + "\" " \
                                                                    "type='button' class='btn fas fa-edit'><span " \
                                                                    "aria-hidden='true'></span></a>" \
                                                                    "<a href=\"" + delete_url + "\" " \
                                                                                                "type='button' class='btn'>" \
                                                                                                "<span aria-hidden='true'>&times;</span></a></div></td>"
                        if_inside = True
                if not if_inside:
                    table_string += "<td></td>"
        table_string += "</tr>"
    pdf_url = reverse('start_page:schools:lessons_panel:render_table', args=[schedule_id])
    table_string += "</tbody><a href=" + pdf_url + " type='button' class='btn btn-danger'>Wyeksportuj do PDF</a>"

    return render(request, 'lessons_panel/schedule_panel.html', {'schedule_selected': schedule_object,
                                                                 'max_lessons': range(1, max_lessons + 1),
                                                                 'schedule_panel': table_string})


class LessonDelete(generic.DeleteView):
    model = Lesson
    template_name = "lessons_panel/lesson_delete.html"

    def get_context_data(self, **kwargs):
        school_id = self.object.schedule.school_id
        context = super(LessonDelete, self).get_context_data(**kwargs)
        context['school'] = get_object_or_404(School, id=school_id)
        context['lesson'] = get_object_or_404(Lesson, id=self.kwargs.get('pk', ))
        return context

    def get_success_url(self):
        school_id = self.object.schedule.school_id
        return reverse_lazy('start_page:schools:lessons_panel:lessons-panel', kwargs={'pk': school_id})


class LessonUpdate(generic.UpdateView):
    model = Lesson
    template_name = "lessons_panel/lesson_edit.html"
    template_name_suffix = '_update_form'
    form_class = LessonForm

    def get_context_data(self, **kwargs):
        lesson_object = Lesson.objects.get(pk=self.kwargs['pk'])
        schedule_object = lesson_object.schedule
        school_id = schedule_object.school_id
        context = super(LessonUpdate, self).get_context_data(**kwargs)
        context['school'] = get_object_or_404(School, id=school_id)
        return context

    def get_success_url(self):
        school_id = self.object.schedule.school_id
        return reverse_lazy('start_page:schools:lessons_panel:lessons-panel', kwargs={'pk': school_id})

    def post(self, request, **kwargs):
        lesson_form = self.form_class(request.POST, instance=self.get_object())
        if lesson_form.is_valid():
            if lesson_form.changed_data:
                obj = lesson_form.save(commit=False)
                lesson_object = Lesson.objects.get(pk=self.kwargs['pk'])
                schedule_object = Schedule.objects.get(pk=lesson_object.schedule_id)
                class_object = lesson_object.class_field
                obj.class_field_id = class_object.id
                obj.schedule_id = schedule_object.id
                obj.save()

templates/lessons_panel/ajax_schedule_table.html
Plan {{ schedule_selected.name }}

templates/lessons_panel/button_select_class.html
<a href="{% url 'start_page:schools:lessons_panel:selected-class' record.id %}"
   type="button" class="btn btn-success far fa-check-circle"></a><!-- fas fa-check-circle -->

templates/lessons_panel/form_schedule_class.html
{% load widget_tweaks %}
{% for field in schedule_object %}
    <div class="form-group">
        <label class="control-label">{{ field.label_tag }}</label>
        <div>{{ field|add_class:'form-control' }}</div>
    </div>
{% endfor %}

templates/lessons_panel/form_template_lessons.html
{% load widget_tweaks %}
{% for field in lesson_form %}
    <div class="form-group">
        <label class="control-label">{{ field.label_tag }}</label>
        <div>{{ field|add_class:'form-control' }}</div>
    </div>
{% endfor %}

templates/lessons_panel/lesson_add.html
{% extends 'start_page/base.html' %}
{% load render_table from django_tables2 %}

{% block title %}
    Panel lekcji
{% endblock %}

{% block body %}
    {% include 'start_page/messages_template.html' %}
    {% include 'start_page/error_template.html' %}

    <div>
        <form id="lesson_form"
          data-schedules-url="{% url 'start_page:schools:lessons_panel:ajax_load_schedules' %}"
          class="form-horizontal" method="post">
        <div class="panel panel-default col-md-2">
            <div class="panel-heading">
                <h3 style="text-align: center;">Wybierz plan</h3>
            </div>
            <div class="panel-body">
                {% csrf_token %}
                {% include 'lessons_panel/form_schedule_class.html' %}

            </div>

        </div>
            <div id="schedule_panel"
                  data-schedule-panel="{% url 'start_page:schools:lessons_panel:ajax_load_schedule_panel' %}">
                {% include 'lessons_panel/schedule_panel.html' %}
            </div>

        <div class="panel panel-default col-md-2">
            <div class="panel-heading">
                <h3 style="text-align: center;">Dodawanie lekcji</h3>
            </div>
            <div class="panel panel-default">
                <div class="col-md-offset-1 col-md-10">
                    <div class="panel-body">
                            {% csrf_token %}
                            {% include 'lessons_panel/form_template_lessons.html' %}
                            <div class="form-group">
                                <form action=""></form>
                                <button id="add_button" type="submit" class="btn btn-info col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-xs-offset-2 col-xs-8
                                col-sm-offset-2 col-sm-8 ">Dodaj</button>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>

    <script>
        let schedule_field = $("#id_schedule");
        $("#id_class_field").change(function () {
          let url = $("#lesson_form").attr("data-schedules-url");
          let classId = $(this).val();
          $.ajax({
            url: url,
            data: {
              'class_field': classId
            },
            success: function (data) {
              schedule_field.html(data);
            }
          });

        });
        if(schedule_field.val()){
            let url = $("#schedule_panel").attr("data-schedule-panel");
            let scheduleId = schedule_field.val();

            $.ajax({
            url: url,
            data: {
              'schedule': scheduleId
            },
            success: function (data) {
              $("#schedule_panel").html(data);

            }
          });
        }
        schedule_field.change(function () {
            let url = $("#schedule_panel").attr("data-schedule-panel");
            let scheduleId = $(this).val();

            $.ajax({
            url: url,
            data: {
              'schedule': scheduleId
            },
            success: function (data) {
              $("#schedule_panel").html(data);

            }
          });
        });
    </script>

{% endblock %}

templates/lessons_panel/lesson_delete.html
{% extends 'delete_form.html' %}
{% block back-href %}
    href={% url 'start_page:schools:lessons_panel:lessons-panel' school.id %}
{% endblock %}
{% block name-delete %}
    lekcje {{ object.lesson_number }} <br> z klasą {{ object.class_field.name }} w pokoju {{ object.room.room_number }}
{% endblock %}

templates/lessons_panel/lesson_edit.html
{% extends 'template_add_edit.html' %}
{% block title %}
    Edycja lekcji
{% endblock %}
{#{% block back-href %}#}
{#    <a type="button" class="btn btn-info col-md-offset-1 col-md-3" href={% url 'start_page:schools:lessons_panel:lessons-panel' school.id %}>Wróć</a>#}
{#{% endblock %}#}
{% block panel-header %}
    Informacje o lekcji:
{% endblock %}
{% block post-button %}
    Zaktualizuj
{% endblock %}

templates/lessons_panel/schedule_panel.html
{% load if_lesson_added %}
<meta http-equiv=Content-Type content="text/html;charset=utf-8">
<div class="panel panel-default col-md-8">
    <div class="panel-heading">
        {% if schedule_selected.name %}
            <h4 id="schedule_table_title" style="text-align: center;">Plan {{ schedule_selected.name }}</h4>
        {% else %}
            <h4 id="schedule_table_title" style="text-align: center;">Plan nie wybrany</h4>
        {% endif %}
    </div>
    <div class="panel-body">
    <table style="font-family: Arial,serif" class="table">
        <thead class="thead-dark">
            <tr>
                <th></th>
                {% for i in max_lessons %}
                    <th>{{ i }}</th>
                {% endfor %}
            </tr>
        </thead>
        {{ schedule_panel|safe }}
    </table>
    </div>
</div>

templates/lessons_panel/schedules_dropdown_list.html
<option value="">---------</option>
{% for schedule in schedules_year %}
<option value="{{ schedule.id }}">{{ schedule }}</option>
{% endfor %}